# .github/workflows/syncWithOrigin.yml

name: Merge upstream branches
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '* * * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'biketagorg'
          git config --global user.email 'biketagorg@gmail.con'

          # "git checkout production" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/keneucker/biketag-website.git
          git fetch upstream

          # Neither forget the -b opt,
          # the feature/x ref is ambiguous at this stage
          # git checkout -b feature/x origin/feature/x
          # git merge --no-edit upstream/feature/x
          # git push origin feature/x

          git checkout production
          git merge --no-edit upstream/production
          git push origin production
